-- CreateTable
CREATE TABLE "registros_seguridad_alimentaria" (
    "id" SERIAL NOT NULL,
    "nombreResponsable" VARCHAR(100) NOT NULL,
    "tipoDocumento" "TipoDocumento" NOT NULL,
    "numeroDocumento" VARCHAR(20) NOT NULL,
    "fechaNacimiento" TIMESTAMP(3) NOT NULL,
    "telefono" VARCHAR(15) NOT NULL,
    "correoElectronico" VARCHAR(100),
    "direccion" VARCHAR(100) NOT NULL,
    "barrio" VARCHAR(100) NOT NULL,
    "comuna" VARCHAR(50) NOT NULL,
    "estratoSocial" "EstratoSocial" NOT NULL,
    "grupoEtnico" "GrupoEtnico" NOT NULL,
    "esAgricultor" BOOLEAN NOT NULL DEFAULT false,
    "tieneTierras" BOOLEAN NOT NULL DEFAULT false,
    "hectareas" DOUBLE PRECISION,
    "pisoTermico" VARCHAR(50),
    "tieneCultivo" BOOLEAN NOT NULL DEFAULT false,
    "tiposCultivo" VARCHAR(100),
    "participacionPrevia" BOOLEAN NOT NULL DEFAULT false,
    "proyectosAnteriores" VARCHAR(100),
    "tieneRiego" BOOLEAN NOT NULL DEFAULT false,
    "tieneHerramientas" BOOLEAN NOT NULL DEFAULT false,
    "tiposHerramientas" VARCHAR(100),
    "tieneAsistenciaTecnica" BOOLEAN NOT NULL DEFAULT false,
    "motivacion" TEXT NOT NULL,
    "tiempoSemanal" VARCHAR(100) NOT NULL,
    "expectativas" TEXT NOT NULL,
    "aceptaTerminos" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "registros_seguridad_alimentaria_pkey" PRIMARY KEY ("id")
);
